import React from 'react';
import Head from 'next/head';
import {
  Card, Navbar, Dropdown, Avatar,
} from 'flowbite-react';
import { signIn, useSession, signOut } from 'next-auth/react';
import Link from 'next/link';
import Image from 'next/image';
import Footer from '../components/Footer';
import styles from '../styles/About.module.css';
import navStyles from '../styles/Navbar.module.css';

const About = () => {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>HireMe | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HireMeHeadNew-light.png" />
      </Head>
      <main className={styles.about}>
        <Card className={styles.aboutContainer}>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Tech Stack
          </h1>
          <div className={styles.techStack}>
            <Image src="/nextjs.png" width={50} height={50} alt="pic" />
            <Image src="/googlemaps.png" width={50} height={50} alt="pic" />
            <Image src="/spring.svg" width={50} height={50} alt="pic" />
            <Image src="/mongo.png" width={50} height={50} alt="pic" />
            <Image src="/vercel.svg" width={50} height={50} alt="pic" />
          </div>
          <div className={styles.techStack}>
            <Image src="/azure.png" width={50} height={50} alt="pic" />
            <Image src="/javascript.png" width={50} height={50} alt="pic" />
            <Image src="/css.png" width={50} height={50} alt="pic" />
            <Image src="/node.png" width={50} height={50} alt="pic" />
            <Image src="/java.png" width={50} height={50} alt="pic" />
          </div>
          <h2 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Further Development
          </h2>
          <ul className="list-disc pl-5 text-gray-500 dark:text-gray-400 text-center ml-2">
            <li>Chat functionality</li>
            <li>Calendar Booking system</li>
            <li>Integrated Payment system</li>
          </ul>
        </Card>
      </main>
      <nav className={navStyles.bottomNav}>
        <div className={navStyles.bottomNavLinks}>
          <Navbar.Link
            href="/">
            Home
          </Navbar.Link>
          <Navbar.Link href="/about">
            About
          </Navbar.Link>
          <Navbar.Link href="/contact">
            Contact
          </Navbar.Link>
        </div>
        <div className={navStyles.bottomNavProfile}>
          {session ? (
            <div className="flex md:order-2">
              <Dropdown
                arrowIcon={false}
                inline
                label={<Avatar alt="User settings" img={session.user.image} rounded />}>
                <Dropdown.Header>
                  <span className="block text-sm">
                    {session.user.name}
                  </span>
                  <span className="block truncate text-sm font-medium">
                    {session.user.email}
                  </span>
                </Dropdown.Header>
                <Dropdown.Item>
                  <Link href="/account">My Account</Link>
                </Dropdown.Item>
                <Dropdown.Divider />
                <Dropdown.Item onClick={() => signOut()}>
                  Sign out
                </Dropdown.Item>
              </Dropdown>
            </div>
          ) : <Link href="/login" onClick={() => signIn()}>Login</Link>}
        </div>
      </nav>
      <div className={navStyles.bottomFooter}>
        <Footer />
      </div>
    </div>

  );
};
export default About;
