import React from 'react';
import Head from 'next/head';
import {
  Card, Navbar, Dropdown, Avatar,
} from 'flowbite-react';
import Link from 'next/link';
import Image from 'next/image';
import { signIn, useSession, signOut } from 'next-auth/react';
import Footer from '../components/Footer';
import styles from '../styles/Contact.module.css';
import navStyles from '../styles/Navbar.module.css';

const Contact = () => {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>HireMe | Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HireMeHeadNew-light.png" />
      </Head>

      <main className={styles.contactMain}>
        <div className={styles.contactContainer}>
          <div className={styles.contact}>
            <Card imgSrc="shalihin.jpeg">
              <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                Shalihin Ahmad
              </h5>
              <div>
                <p className="font-semibold text-gray-700 dark:text-gray-400 font-">
                  Java Fullstack Developer
                </p>
                <p className="text-sm text-gray-700 dark:text-gray-400">
                  mohamad.ahmad@salt.dev
                </p>
              </div>

              <p>
                I&apos;m a young professional from Singapore who brings
                eagerness and passion to thrive as a developer, with a
                willingness to go the extra mile in challenging
                situations. Dependability and logical thinking are my
                strongest traits and while in a team, no one gets left
                behind.
              </p>
              <div className={styles.logoLinks}>
                <Link href="https://www.linkedin.com/in/shalihinahmad/">
                  <Image src="/linkedln.png" width={40} height={40} alt="pic" />
                </Link>
                <Link href="https://github.com/omgshalihin">
                  <Image src="/GitHub-Mark-120px-plus.png" width={33} height={33} alt="pic" />
                </Link>
              </div>
            </Card>
          </div>
          <div className={styles.contact}>
            <Card imgSrc="ariel.jpeg">
              <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                Ariel Shaka
              </h5>
              <div>
                <p className="font-semibold text-gray-700 dark:text-gray-400 font-">
                  Java Fullstack Developer
                </p>
                <p className="text-sm text-gray-700 dark:text-gray-400">
                  ariel.yumembudi@salt.dev
                </p>
              </div>
              <p>
                I&apos;m a very curious person,
                passionate about technology
                in general and problem solving.
                I find satisafaction in
                building products that would
                have a positive impact on peoples life.
                I love being challenged and pushed to
                think outside the box.
              </p>

              <div className={styles.logoLinks}>
                <Link href="https://www.linkedin.com/in/arielshaka">
                  <Image src="/linkedln.png" width={40} height={40} alt="pic" />
                </Link>
                <Link href="https://github.com/ArielShaka">
                  <Image src="/GitHub-Mark-120px-plus.png" width={33} height={33} alt="pic" />
                </Link>
              </div>
            </Card>
          </div>

          <div className={styles.contact}>
            <Card imgSrc="filipe.jpeg">
              <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                Filipe Forssblad
              </h5>
              <div>
                <p className="font-semibold text-gray-700 dark:text-gray-400 font-">
                  Java Fullstack Developer
                </p>
                <p className="text-sm text-gray-700 dark:text-gray-400">
                  filipe.forssblad@salt.dev
                </p>
              </div>
              <p>
                {' '}
                I&apos;m a Portuguese-Swede living in Stockholm,
                passionate about learning and solving complex
                problems. Coding is the realized outlet
                of these passions.
                <br />
                I am cheerful and proactive, comfortable working
                alone and in teams under a tight schedule.
                {' '}
              </p>
              <div className={styles.logoLinks}>
                <Link href="https://www.linkedin.com/in/filipera88/">
                  <Image src="/linkedln.png" width={40} height={40} alt="pic" />
                </Link>
                <Link href="https://github.com/FilipeRA">
                  <Image src="/GitHub-Mark-120px-plus.png" width={33} height={33} alt="pic" />
                </Link>
              </div>
            </Card>
          </div>
        </div>
      </main>
      <nav className={navStyles.bottomNav}>
        <div className={navStyles.bottomNavLinks}>
          <Navbar.Link
            href="/">
            Home
          </Navbar.Link>
          <Navbar.Link href="/about">
            About
          </Navbar.Link>
          <Navbar.Link href="/contact">
            Contact
          </Navbar.Link>
        </div>
        <div className={navStyles.bottomNavProfile}>
          {session ? (
            <div className="flex md:order-2">
              <Dropdown
                arrowIcon={false}
                inline
                label={<Avatar alt="User settings" img={session.user.image} rounded />}>
                <Dropdown.Header>
                  <span className="block text-sm">
                    {session.user.name}
                  </span>
                  <span className="block truncate text-sm font-medium">
                    {session.user.email}
                  </span>
                </Dropdown.Header>
                <Dropdown.Item>
                  <Link href="/account">My Account</Link>
                </Dropdown.Item>
                <Dropdown.Divider />
                <Dropdown.Item onClick={() => signOut()}>
                  Sign out
                </Dropdown.Item>
              </Dropdown>
            </div>
          ) : <Link href="/login" onClick={() => signIn()}>Login</Link>}
        </div>
      </nav>
      <div className={navStyles.bottomFooter}>
        <Footer />
      </div>
    </div>
  );
};

export default Contact;
