import React, { useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Image from 'next/image';

import {
  Navbar, Dropdown, Avatar, Button,
} from 'flowbite-react';
import { signIn, useSession, signOut } from 'next-auth/react';
import Link from 'next/link';
import Footer from '../components/Footer';
import navStyles from '../styles/Navbar.module.css';

const Login = () => {
  const { data: session } = useSession();
  const router = useRouter();

  useEffect(() => {
    router.push('/account');
  }, []);

  return (
    <>
      <Head>
        <title>HireMe | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/HireMeHeadNew-light.png" />
      </Head>
      <main className="bg-white dark:bg-gray-900 login-main-container">
        <div className="login-main-container-div flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0 align-middle self-center">
          <Image src="/HireMeNew.png" className="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white" width={300} height={300} alt="company logo" />
          <div className="w-0.5 bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div className="flex flex-col p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 className="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                Welcome back
              </h1>
              <Button type="submit" onClick={() => signIn()} color="gray">
                <Image src="/google.png" height={20} width={20} alt="google-sign-in" />
                <h2>Log in with Google</h2>
              </Button>
            </div>
          </div>
        </div>
      </main>
      <nav className={navStyles.bottomNav}>
        <div className={navStyles.bottomNavLinks}>
          <Navbar.Link
            href="/">
            Home
          </Navbar.Link>
          <Navbar.Link href="/about">
            About
          </Navbar.Link>
          <Navbar.Link href="/contact">
            Contact
          </Navbar.Link>
        </div>
        <div className={navStyles.bottomNavProfile}>
          {session ? (
            <div className="flex md:order-2">
              <Dropdown
                arrowIcon={false}
                inline
                label={<Avatar alt="User settings" img={session.user.image} rounded />}>
                <Dropdown.Header>
                  <span className="block text-sm">
                    {session.user.name}
                  </span>
                  <span className="block truncate text-sm font-medium">
                    {session.user.email}
                  </span>
                </Dropdown.Header>
                <Dropdown.Item>
                  <Link href="/account">My Account</Link>
                </Dropdown.Item>
                <Dropdown.Divider />
                <Dropdown.Item onClick={() => signOut()}>
                  Sign out
                </Dropdown.Item>
              </Dropdown>
            </div>
          ) : <Link href="/login" onClick={() => signIn()}>Login</Link>}
        </div>
      </nav>
      <div className={navStyles.bottomFooter}>
        <Footer />
      </div>
    </>
  );
};

export default Login;
